### PR TITLE
revised request - restored deleted characters

### PR DESCRIPTION
**Pull request by fkast**
Sorry!  I dropped two characters to 004. Now restored.

### CODE REVIEW

**Comment by danielneilson** [comment]
Thanks for the contribution! I merged, fixed some issues with spaces (just to keep the file clean) and added your name to the list of contributors.

**Comment by danielneilson** [comment]
BTW I'd be interested to hear what your thoughts were about the translation---whether anything was particularly difficult to render in Albanian, or felt unnatural, or whether there were things that you thought were missing.

**Comment by aaronkyle** [comment]
I imagine that it would be interesting for Dan to hear about your two
"main" dialects in Albanian, how these differ from the 'official' language,
and how you'd write and say things differently in informal speech in each
of the two main dialects (and sub-dialects).

On Wed, Oct 7, 2015 at 11:56 AM, Daniel H. Neilson <notifications@github.com

**Comment by danielneilson** [comment]
Yes I certainly would...

**Comment by fkast** [comment]
Yeah, like Aaron pointed out the dialect, that did kind of make it difficult to translate maybe every single passage, because college phrases between students and professors are not formal, at least not in Albania/Kosovo. 

The Albanian language has two main dialects Gheg and Tosk, and also the standard language which consists mostly of Tosk words. So passages like these are entirely informal and in either one of the two dialect, but even these two dialects split into "sub-dialects" which are locally based. 

Usually everyone talks in their own "sub-dialect" because everyone else can understand all of the other "sub-dialects", since a "sub-dialect" can consist of new words, but it is mainly usage of the same letter in nearly all the words.
For example in Tosk  a lot of words end in "ë", while in Gheg the same words end in "a". In one "sub-dialect" these words can end in "a" but in another "sub-dialect" (say another city in the Gheg region) they would end in "o".

So in general, whenever we have to translate we translate to the standard Albanian language, which in itself is very formal, since we only use it in schools, newspapers, newscasts etc.

I hope I was not confusing, but try to think of it as German I think, where there is the standard language, but people in different parts talk in their own "sub-dialect" or whatever it is called.

PS. Another thing that made it kind of hard to translate, is the different school system, for example we do categorize courses with hundred-level say 100-level, Physis101 etc. Also, I do not think we use "credits" in our education system. So for such words, I tried to translate them to the closest/most common word/phrase I though was best.

**Comment by danielneilson** [comment]
Interesting. Although these precise details are particular to Albanian, we may encounter related problems with other languages. I will probably try to expand the instructions for translation at some point to give a bit more guidance. Right now we have Spanish and Russian outstanding, so I'll wait to see what the contributors say about those translations.

Though I do not speak Albanian, I was nonetheless able to spot a translation error in 0002, so if you get a chance, maybe you could read through everything one more time to make sure you're happy with the translations. Pull the latest version from my repo before you make any changes.

**Pull request merged**
